### ISSUE TITLE
inspect default parameter from method object

### ISSUE THREAD

**Issue by ipmsteven** [jasonrclark/hometown#3]
Hi @jasonrclark 

This question may not related to hometown gem.

I am wondering if there is a way to inspect the default parameter for a method or proc object in ruby?

From [ruby-doc](http://ruby-doc.org/core-2.2.0/Method.html#method-i-parameters), I can only get a list of parameter names, if I set a default value for a parameter, is there a way to inspect it?  

Thanks

**Comment by jasonrclark** [comment]
Hey @ipmsteven, good question.

From my investigation, I don't see any way to get at the defaults from a method. That restriction actually makes sense when you remember that those values can be dynamic.

Take this class for example:

```
class Defaulter
  attr_accessor :value
  def my_method(value = @value)
    ...
  end
end
```

The exact default would depend on the instance of `Defaulter` that you're actually holding onto. Even further, Ruby lets you get an "unbound" copy of the method:

```
Defaulter.instance_method(:my_method)
=> #<UnboundMethod: Defaulter#my_method>
```

In this case, even if Ruby had a way to try and return you the defaults, it can't know what they are against that method.

Interesting question, and thanks for asking. I learned something about Ruby by trying to figure it out.

**Comment by ipmsteven** [comment]
cool, thanks for your explanation. I also learned a lot @jasonrclark  :smile:
